# docker-compose.yml
# Orchestration multi-services
version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: .
    ports:
      - "7860:7860"
    command: python frontend/app.py
    depends_on:
      - backend
    environment:
      BACKEND_URL: "http://backend:8000"